.github/workflows/build.yml
CONTRIBUTING.md

Adding CONTRIBUTING (with basic information on how to set up local repo environment) and Github build action (Python 3.7 to 3.9).

Actions build

---

core/utils.py
modules/base/errors/__init__.py
modules/base/errors/exceptions.md
modules/base/errors/lang.cs.ini
modules/base/errors/lang.en.ini

I's nowhere near perfect, but it's a start. I found out that alphabetical ordering is not working, it should probably be sorted as it appears in the documentation/in the hierarchy list.

Added Errors module

---

core/log.conf
core/logs.py
modules/__init__.py
modules/base/errors/__init__.py
modules/base/info.py
modules/info.txt
pumpkin.py

- Send selected errors to log file
- Change the logger output so the time and level columns are aligned

Errors: link module to logging

---

core/help.py
core/lang.cs.ini
core/lang.en.ini
core/text.py
core/utils.py
modules/base/admin/__init__.py
pumpkin.py

- The help is formatted as in Rubbergoddess, with quotes & bold fonts
- Text: Default language is `en` instead of `cs`
- Added TODOs to Admin to save module changes to database

Add Help formatting

---

core/utils.py
modules/base/admin/__init__.py
modules/base/admin/lang.cs.ini
modules/base/admin/lang.en.ini

I added the `pumpkin` command for changing the name and the avatar. I also added the `@staticmethod` decorators to `Utils` functions

Admin: Add name and avatar change commands

---

.flake8
.github/workflows/build.yml
.gitignore
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
core/lang.cs.ini
core/lang.en.ini
core/text.py
core/utils.py
modules/base/__init__.py
modules/base/admin/__init__.py
modules/base/admin/lang.cs.ini
modules/base/admin/lang.en.ini
modules/base/info.py
pumpkin.py
requirements-dev.txt
requirements.txt
tests/test_core_utils.py
tests/test_modules_base_admin.py

Adds options to download, update and delete GIT repositores with additional code.

Repository management

---

.github/workflows/build.yml
core/config.py
core/text.py
database/__init__.py
database/config.py
pumpkin.py

Implemented the Core bot database table, with default inicialization.
It would probably be best if the config object would be used instead of copying its values in case they get changed during execution.

Core bot database table

---

core/utils.py
database/__init__.py
modules/base/admin/database.py
modules/base/admin/lang/cs.ini
modules/base/admin/lang/en.ini
modules/base/admin/module.py
modules/base/base/database.py
pumpkin.py
requirements-dev.txt
requirements.txt

Add "auto" keyword to config to allow automatic status updating based on API latency.
This must be merged after #29.

Autostatus

---

.pre-commit-config.yaml
core/acl.py
database/acl.py
modules/base/acl/lang/cs.ini
modules/base/acl/lang/en.ini
modules/base/acl/module.py
pumpkin.py
requirements-dev.txt
requirements.txt

This is second part on the ACL, following PR #33.

ACL: Check function

---

.github/workflows/build.yml
core/logging.py
database/__init__.py
pumpkin.py
tests/language_file_checker.py

I just had to silence a few print()s we are using to log important information

Fix flake8 warnings

---

core/help.py
core/lang/cs.ini
core/lang/en.ini
core/text.py
core/utils.py
database/language.py
modules/base/acl/lang/cs.ini
modules/base/acl/lang/en.ini
modules/base/admin/lang/cs.ini
modules/base/admin/lang/en.ini
modules/base/base/lang/cs.ini
modules/base/base/lang/en.ini
modules/base/errors/lang/cs.ini
modules/base/errors/lang/en.ini
modules/base/language/lang/cs.ini
modules/base/language/lang/en.ini
modules/base/language/module.py
modules/base/logging/lang/cs.ini
modules/base/logging/lang/en.ini
requirements.txt
tests/test_core_utils.py

This PR adds dynamic language to the help command. There are still some minor issues: the module description isn't rendered.
As a side effect, the module description section has to be named `[_]` instead of `[module]`.
Because of the caching (see commit descriptions), I'm adding `ring` package as dependency.

Help localization

---

core/exceptions.py
modules/base/acl/module.py
modules/base/admin/module.py
modules/base/base/module.py
modules/base/errors/lang/cs.ini
modules/base/errors/lang/en.ini
modules/base/errors/module.py
modules/base/logging/module.py
pumpkin.py

This allows modules that require some `.env` variables to announce that their variable is not set.
All strings should now be fully translatable.

Add DotEnvException and l10n to all the modules

---

core/__init__.py
core/text.py
core/utils.py
modules/base/base/database.py
modules/base/base/lang/cs.ini
modules/base/base/lang/en.ini
modules/base/base/module.py

See individual commits and their descriptions.
This PR is a bit noisy, feel free to squash the commits before merging them.

Base: Add database implementation of user reaction functionalities: pinning, bookmarking and (WIP) threads

---

core/exceptions.py
modules/base/errors/lang/cs.ini
modules/base/errors/lang/en.ini
pumpkin.py

- Add ModuleException
- Catch unavailable modules on bot load

Add ModuleException, catch missing modules on bot load

---

modules/base/base/module.py

- The message was retrieved in every function, I've moved the code
to the common part.
- Message type check has been added, to disallow the actions on
system messages.

Base: Code flow enhancement

---

core/text.py
database/language.py
docs/installation/02-direct.rst
docs/installation/_database.rst
modules/base/__init__.py
modules/base/admin/lang/cs.ini
modules/base/admin/lang/en.ini
modules/base/admin/module.py
modules/base/errors/module.py
modules/base/logging/module.py
requirements-dev.txt
requirements.txt

After attempting to follow the docs I found some issues which this PR fixes.

Small fixes for the core functionality

---

.pre-commit-config.yaml
core/acl.py
core/help.py
core/logging.py
database/acl.py
database/logging.py
modules/base/acl/lang/cs.ini
modules/base/acl/lang/en.ini
modules/base/acl/module.py
modules/base/admin/lang/cs.ini
modules/base/admin/lang/en.ini
modules/base/admin/module.py
modules/base/errors/lang/cs.ini
modules/base/errors/lang/en.ini
modules/base/errors/module.py
modules/base/logging/lang/cs.ini
modules/base/logging/lang/en.ini
modules/base/logging/module.py
requirements-dev.txt
requirements.txt

- Admin: Database fixes
- Admin: Removed 'pumpkin' command with its subcommands
- Errors: Improve error logging 
- Logging: Several updates and fixes
- Logging: Added logging
See commit messages for details.

Various fixes.

---

docs/installation/03-config.rst
modules/base/admin/lang/cs.ini
modules/base/admin/lang/en.ini
modules/base/admin/module.py

- Docs: Add restore phase of the database
- Admin: Add 'pumpkin shutdown' & 'pumpkin restart' commands
- Admin: Remove old unused language strings

Small Admin and docs changes

---

modules/base/admin/lang/en.ini
modules/base/errors/lang/cs.ini
modules/base/errors/lang/en.ini
modules/base/errors/module.py

- Errors: Include exception argument in ChannelNotReadable
- Admin: Fix 'repository install' string 'reply' in English

Update Admin & Error modules

---

docs/installation/01-docker.rst
docs/installation/_database.rst

- cleared confusion around the .env file
- cd in docker installation required  - added to the docs

Updated documentation

---

modules/base/base/lang/cs.ini
modules/base/base/lang/en.ini
modules/base/base/module.py

Just activated already written code and made some small tweaks. Now pumpkin needs to run in an environment with  the Discord.py 2.0 library installed!

Threads implemented, yaay. 

---

docs/development/repository.rst
modules/base/admin/module.py

Missing kwargs, documentation typo

---

core/acl.py
core/check.py
core/lang/cs.ini
core/lang/en.ini

Resolves: #80
Decorator version function checks minimum version of discord.py and replies to user if command is not available.

Added discord.py min. version checking

---

modules/base/base/database.py
modules/base/base/lang/cs.ini
modules/base/base/lang/en.ini
modules/base/base/module.py

- Rename AutoPin to UserPin (`ALTER TABLE base_base_autopin RENAME TO base_base_userpin`)
- Rename AutoThread to UserThread (`ALTER TABLE base_base_autothread RENAME TO base_base_userthread`)
- **New** AutoThread allows you to create channel that has a thread created automatically for every new message. This is useful for #help channels.

Add AutoThread functionality

---

modules/base/base/database.py
modules/base/base/lang/cs.ini
modules/base/base/lang/en.ini
modules/base/base/module.py

- New database column
- 'autothread set' command changed

Autothread Duration added

---

modules/base/admin/lang/cs.ini
modules/base/admin/module.py
modules/base/admin/objects.py
tests/test_modules_base_admin.py

This commit updates the repository logic to make it much easier
interacting with repositories.

Update repository management

---

.github/workflows/build.yml
core/__init__.py
core/i18n.py
docs/development/translations.rst
gettext.py
modules/base/admin/module.py
modules/base/base/module.py
modules/base/po/cs.po
modules/base/po/sk.po
requirements.txt

Only the Base module has been updated. Others will have to be converted before the old translation system can be removed from the codebase.

Update language system

---

.gitignore
modules/base/admin/objects.py
tests/test_modules_base_admin.py

Mainly updates to the Admin: fixed one false negative (repository with just one module) and added requirements for module directories.

Maintenance updates

---

core/logging.py

Log filename changed

---

core/utils.py

PR to resolve issue #77 
No more HTTPErrors occuring because of blocked DMs.

New dm handler

---

modules/base/base/module.py

Resolves issue #92 
- If a message gets deleted, its thread gets archived or deleted (if the thread is empty).
- Also logging for this behavior implemented.

Threads on message deletion

---

Dockerfile
default.docker.env
docker-compose.yml
docs/installation/01-docker.rst

- Fixed SELinux bug in `docker-compose.yml`
- Bumped versions in `Dockerfile`
- added new container to `docker-compose.yml` to automatically backup the database (created a default.docker.env for it)
- Updated Docs

Better docker

---

Dockerfile
core/po/cs.popie
core/po/sk.popie
core/utils.py

- Embed pagination provided by `core/utils.py/ScrollableEmbed`
- fixed Dockerfile volume
- see implementation at [pumpkin-py/pumpkin-fun/urban/module.py#L124](https://github.com/pumpkin-py/pumpkin-fun/blob/233b46172a8d289c86703efd385944c2722e6ee4/urban/module.py#L124)

Implemented embed pagination

---

core/help.py
modules/base/acl/module.py
modules/base/admin/module.py
modules/base/base/module.py
modules/base/errors/module.py
modules/base/language/module.py

Finally fixed all module translations

---

Dockerfile

effectively using a multistage build

Docker now automatically installs required python libraries from every module

---

core/i18n.py
modules/base/base/module.py

Moar fixes

---

core/logger.py

Core: Include guild information in Discord-side logs

---

core/utils.py
requirements.txt
tests/test_core_utils.py

Improved it from when it was in the Unverify module

Added parse_datetime to utils

---

.pre-commit-config.yaml
core/help.py
modules/base/admin/module.py
requirements-dev.txt

See individual commits for details

Various non-code updates

---

.flake8
modules/base/errors/module.py
modules/base/po/cs.popie
modules/base/po/sk.popie

These two error exceptions should be handled correctly since we can meet with them soon or later.

Added two error messages

---

pie/po/cs.popie
pie/po/sk.popie
pie/utils/__init__.py
pie/utils/objects.py

Based on Discord discussion I've made this simple way to ask users for confirmation.
There's example of using this: https://github.com/ArcasCZ/pumpkin-reminder/tree/core-changes

Implement ConfirmView

---

pie/utils/objects.py
pie/utils/text.py

There's typo in docs and assigning message to local variable instead of class variable.

Objects: Fix docs

---

pie/po/cs.popie
pie/po/sk.popie
pie/utils/objects.py

I've changed ScrollableEmbed so it now uses View and buttons instead of reactions.
It now looks like this:

Utils: Use View in ScrollableEmbed

---

modules/base/admin/module.py

Admin: Fix i18n issues

---

docs/development/imports.rst
docs/development/logging.rst
docs/development/repository.rst

- Fix imports
- Fix references to discontinued template repository
- Use space indentation everywhere
Resolves #211

Docs: Fix outdated information

---

modules/base/admin/module.py
modules/base/admin/objects.py
modules/base/po/cs.popie
modules/base/po/sk.popie

I've slightly reworked repo updating. Now updates are not force by default, but instead there's option to force update or perform hard reset.

Admin: Force and reset update options

---

modules/base/base/module.py

Base: Fix autopin bothering messages

---

docs/installation/03-development.rst
docs/installation/_token.rst

- Add Message Content intent
- Add token creation to development installion

Docs: Update installation manual

---

pie/utils/objects.py

- moved lock button to middle (between left and right) - it looks overall better
- added `VotableEmbed` extending `nextcord.Embed` and providing callbacks for vote up, neutral and down
- added `ScrollableVotingEmbed` with 3 buttons (vote up, neutral and down) which extends `ScrollableEmbed`
Image of ScrollableVotingEmbed (without scrolling):

Pie: Add ScrollableVotingEmbed + minor tweak

---

pie/help.py

This makes the help output a bit cleaner, you can navigate through
a little bit faster.

Help: Print all command groups and then all final commands

---

pie/utils/text.py
tests/pie/utils/test_text.py

- Increase inter-column spacing to two spaces to increase readability
- '.rstrip()' each line to save characters; this way the lines are not
left-justed if not necessary.

Utils: Update table generation

---

.gitignore
docs/conf.py
docs/installation/03-development.rst
docs/installation/_database.rst
modules/base/admin/module.py
modules/base/base/module.py
modules/base/language/module.py
modules/base/logging/module.py
modules/base/po/cs.popie
modules/base/po/sk.popie
pumpkin.py

See individual commits for details

Various small non-breaking changes

---

.flake8
.pre-commit-config.yaml
pie/po/sk.popie
requirements-dev.txt
requirements.txt

And fix one issue found by PoPie 1.8.0

Update pre-commit package versions

---

pie/po/cs.popie
pie/po/sk.popie
pie/utils/objects.py

This allows dev to create embed with positive-vote only, which could be used to confirm action by multiple members, such as confirm role tagging.

Pie: Add VoteEmbed

---

modules/base/base/module.py
modules/base/po/cs.popie
modules/base/po/sk.popie

Base: fixed different interfaces. 

---

modules/base/base/module.py

When the bookmark is successfully created, all "🔖" reactions are deleted. Also there is now anti-spam cache lasting up to 15 minutes that prevents Bookmark spamming. Resolves #112.

Base: Fixed Bookmarking inconsistency

---

modules/base/base/module.py

This logging is kept in each guild individually. No bot logs.
Resolves #258.

Base: Logging user join & leave events.

---

pie/utils/text.py
tests/pie/utils/test_text.py

- Refactored the code to be easier to maintain
- Added ANSI color support (disabled by default for now)

utils: Refactor utils.text.create_table

---

docs/development/installation.rst
docs/development/repository.rst

Hi, this MR/PR contains the docs enhancement for first time developers.
For the installation part of the development section - there was missing an important part of exporting environment variables. This is mention in [production section](https://pumpkinpy.readthedocs.io/en/latest/production/direct.html#downloading-the-code).
For repository setting - the link for how to import and load module was added. On the main page is a link to user docs but it's easy to skip it. 
In my point of view, these additions are valid. I personally tried run the core and adding the module and these two things were a little confusing. Was able to figured it out by myself but for less experienced developers this can be blocker. For experienced devs, this can make it easier to set up the bot.

Developer documentation enhancement

---

pumpkin.py

Threads were not started correctly

Fix internal event loop issues

---

pie/po/sk.popie

i18n: Update sk.popie

---

modules/base/po/sk.popie
pie/po/sk.popie

Modules-base-po-sk

---

modules/base/base/module.py

The `.flatten()` is not supported in discord.py 2.x

Base: Fix list flattening

---

modules/base/admin/module.py
modules/base/po/cs.popie
modules/base/po/sk.popie
pie/repository/__init__.py

- Make 'repository list' return table
- Include git hashes and topics

Admin: Update 'repository list'

---

pie/utils/objects.py

This adds CommandParser class which patches ArgumentParser, that calls sys.exit(2) on incorrect command.

Add CommandParser (ArgumentParser patch)

---

Dockerfile

Fixes pumpkin-py/pumpkin-py#313

Dockerfile better requirements installation and version bump

---

Dockerfile

added `--no-cache-dir` to `pip install` commands

a clean container is a happy container

---

modules/base/__init__.py
modules/base/backup/module.py
modules/base/po/cs.popie
modules/base/po/sk.popie
modules/base/repo.conf

This submodule downloads all emojis of the current discord guild and uploads them in a zipfile for users to download.

Downloading emoji packs from guilds

---

pie/utils/time.py

Now your bot won't wake me up at 3am when I wanted a reminder in 3 hours instead.

Make regex case insensitive
