pumpkin-py/pumpkin-py

.github/workflows/build.yml
I'm adding one more step to the Actions build. It's only calling `flake8`'s extensions for detecting `print()`s and `TODO`s so they are easily accesible.
=> GH Actions: Run flake8-print & flake8-todo extensions

core/logs.py, requirements.txt
Bot build in docker container was failing so I added the required package.
Logs had a bug where the next rollover time was not computed so rollovers were happening constantly after the first one. I didn't realize it needs to be computed during execution of the doRollover() method. Added that functionality.
=> Requirements fixed + Logs bugfix

.github/workflows/build.yml, CONTRIBUTING.md, core/log.conf, database/__init__.py, database/config.py, database/info.txt, modules/base/admin/__init__.py, modules/base/base/__init__.py, modules/base/base/database.py, modules/base/errors/__init__.py, pumpkin.py, tests/test_languages.py
The `database.initiate()` imports all classes from `modules/<repo>/<module>/database.py` and creates their tables.
There is some issue with this current implementation -- when the module is reloaded, an exception is thrown:
```
This declarative base already contains a class with the same class name
and module name as modules.base.base.database.BaseBasePin, and will be
replaced in the string-lookup table.
```
When `__table_args__ = {"extend_existing": True}` is added to the model definition, only warning is logged, but it works as nothing is thrown. This is rather a workaround than a solution, it should be investigated more.
=> Add dynamic database file loading

modules/base/admin/module.py
Allow modules with same name from different repositories.
Before, if there were two modules A.Foo, B.Foo and A.Foo was loaded, the B.Foo also displayed as loaded. That's because only module names were being compared.
Now the module repository is also taken into account, which allows us to draw them correctly depending on their real loaded/non-loaded state.
=> Base: A 'repository list' patch

docs/development/index.rst, docs/development/logging.rst, docs/development/repository.rst, docs/development/translations.rst, docs/getting-started/index.rst, docs/index.rst, docs/installation/03-config.rst, docs/installation/index.rst
Some of the information (mainly on 3rd party repositories) contain information that has not yet been merged: currently the modules are directly inside of the `modules/` directory, but they will have to be moved one layer deeper to allow us to add tests and another helper scripts or data.
=> Docs: Add information about the bot/framework development

modules/base/errors/lang/cs.ini, modules/base/errors/lang/en.ini, modules/base/errors/module.py
- ExpectedClosingQuoteError: Do not try to say which quote is wrong, just say some is. Probability of mixing multiple quotes is low, and in case of multiple arguments the type of quote won't say much either.
- UserInputError: Do not forward to log, don't report content to user.
=> Errors: Fix two cases of error handling

docker-compose.yml
Rolled back the docker-compose version so that it can be run on older docker-compose
=> docker-compose version rollback

modules/base/base/module.py
- autothread group got an alias "autothreads"
- if a user wants to open a thread inside of a thread, the code will now handle this without logging an exception
=> Threads: Fixed logging and small tweaks

modules/base/acl/module.py
Those indexes were removed some time before, this was forgotten here.
=> ACL: Remove 'del' for index in rule

modules/base/admin/module.py, modules/base/language/module.py
Until now the supported languages were hardcoded on serveral places. Now
the bot will use the LANGUAGES variable specified in the core package.
Because the default is English, 'en' is not specified in that tuple.
Because of that, the functions that allow users to pick an interaction
language have to add the 'en' option where applicable.
=> Admin, Base: Use global LANGUAGES variable

core/utils.py
If you create paginated embed, it causes error "'staticmethod' object is not callable".
=> Fix "'staticmethod' object is not callable"

core/help.py, modules/base/acl/module.py, modules/base/admin/module.py, modules/base/base/module.py, modules/base/errors/module.py
Fixed replacing arguments before translation.
Example:
```Python
_(ctx, "Text {replace}".format(replace=replace))```
=> Fixed translation

modules/base/base/module.py
- discord.py 1.x way of using avatars was being used
- We didn't take into account guild preference
- We didn't take into account possibility of absence of preference
- The i18n string was being used incorrectly
=> Base: Fix bookmark creation

core/logger.py
When using `@tasks.loop()` there is no way to access the context so in case we need to log something on guild level it is necessary to allow guild_log even without specifying a user or a channel.
=> Logger allow guild_log use without context

core/po/cs.popie, core/po/sk.popie, core/utils.py
Simpler usage, handles empty lists, handles lists of length 1
Usage:
```py
scrollable_embed = utils.ScrollableEmbed(ctx, embeds)
await scrollable_embed.scroll()
```
=> Reworked ScrollableEmbed

.pre-commit-config.yaml, modules/base/base/module.py
Recent versions of PoPie warn on 'tc' being used instead of 'utx'.
=> Update pre-commit versions and fix new issues

modules/base/base/module.py
This is probably happening when the message is deleted inside of thread.
=> Base: Handle missing channel on message deletion

pie/logger/__init__.py, tests/__init__.py
- We could (apparently) get a logger instance without a bot attribute
- We'll artifitially make up source channel if there is not one
- Fixed bad attribute access in '_maybe_send()'
=> Core: Fix several logger issues

pie/utils/text.py
There should be option not to sanitize `@` char by adding ZERO_WIDTH_SPACE after this character. It should be used in pumpkin-management's Verify module, 'cause there's logged e-mail address and when you copy this address, it's copied with this symbol and thus it's causing trouble in other commands, such as rwhois.
=> Utils: Option to not sanitize tags

pie/utils/objects.py
If the original message was deleted before timeout, bot would got 404 error. This should be better (however it does not fix all edge cases)
=> Utils: ConfirmView 404 fix

modules/base/base/module.py
We should be deleting the threads only if they were created
automatically. This functionality handles threads that were created from
a message sent by accident, it is not cleaning function that would
manage all orphaned threads.
=> Base: Update thread deletion handling

pie/i18n/__init__.py, pie/po/cs.popie, pie/utils/objects.py
Previously, the language preference of the issuer was used. Now we will
be using language of the user that clicked on interaction.
Additional changes:
- Fix one related czech string.
- Make TranslationContext init arguments optional.
Resolves #197
=> Core: Fix language of ScrollableEmbed replies

modules/base/admin/module.py, modules/base/po/cs.popie, modules/base/po/sk.popie
When a repo which uses database is cloned, no table is created
automatically. Now the bot will send a note that restart is required.
Resolves #191
=> Admin: Send a warning about database on repository install

modules/base/admin/objects.py, tests/modules/base/test_admin.py
They cannot appear as a first character, but they are allowed otherwise
=> Admin: Allow numbers in module/repository names

docker-compose.yml, modules/base/errors/module.py, modules/base/po/cs.popie, modules/base/po/sk.popie, pumpkin.py
I reworked the error handling. It should be more readable and extensible now.
All nextcord related exceptions should be handled separately and any other exception is handled as an unknown error.
I created the CZ popie, so someone needs to take a look at the SK variant too. Once that is finished and @sinus-x takes a look at the recursion prevention stuff we can merge this.
=> Reworked errors

pie/utils/objects.py
If those two ID's are compared using `is` or `is not`, this check fails in case of PM.
=> Objects: Fix Views in PM

pie/help.py
Previously the help did not show any difference between commands and
command groups:
> – **acl mapping**: Manage mapping of ACL levels to roles.
> – **acl overwrite-list**: Display active overwrites.
Now, ellipsis has been added after the names of command groups, and
en dash is used instead of colon to help separate the content:
> — **acl mapping** ... – Manage mapping of ACL levels to roles.
> — **acl overwrite-list** – Display active overwrites.
=> Help: Add '...' after help's subcommand if it is command group

pie/utils/objects.py
If this is not checked, this function takes all unknown ID's as page right button. Could cause problems with intended inheritance in my planned feature ScrollableVotingEmbed.
=> Pie: ScrollableEmbed interaction ID filter

pie/utils/objects.py
I've noticed that if someone delete ScrollableEmbed message and View timed out, bot threw NotFound exception into log.
Also, I've noticed that when Views are timed out, they are binded again into message. This should be handled by not sending view parameter in message.edit(...), but to be explicit I've added None as value.
=> Pie: Fix NotFoundError and binding timeouted view

pumpkin.py
This change enables sets 'ignore_extra' attribute of all non-group
commands to False. When this is applied, bot won't allow additional
words after all known arguments (greedy '*' still works).
Only minority of commands will need to be changed -- 'fun:flip' for
example.
=> Core: Do not ignore extra arguments

default.docker.env, docker-compose.yml
If you are using other than provided PostgreSQL server in docker or with different settings, you might run into trouble that automatic backup is useless. This solves the problem by moving backup environment settings into .env file.
=> Docker: Move backup env to .env

pie/database/__init__.py, pie/storage/__init__.py, pie/storage/database.py
I think it's not a good idea to create whole DB for one key-value configurable pair. For this reason I've come with this - Pie core util called Storage, that would provide dev's their own space for few key-value pairs, such as basic bot or guild configs for functions.
This is my first idea and it's to discuss if there's anything to change. It's still untested.
=> Add global value storage

modules/base/base/database.py, pie/logger/__init__.py, pie/logger/database.py
In Base.Autothread, the database would not update if the settings changed,
now fixed.
In Logger, the deletion of log channel would not be persistent after restart,
now fixed.
Resolves #196
=> Base & Logger: Fixed DB inconsistency

modules/base/admin/module.py, modules/base/logging/module.py, modules/base/po/cs.popie, modules/base/po/sk.popie
All text tables are now using `utils.text.create_table()`.
Resolves #150
=> Unify all ASCII tables

modules/base/admin/module.py
This shorthand may be used by some other command, as it is quite common
word and possible functionality. It is being removed so we don't pollute
the command name pool.
=> Admin: Remove 'spam' alias from spamchannel command

docs/general/index.rst
The General page may not be suitable for general everyday developers, as
they tend to start running commands as they see them. This is an attempt
to direct them to more appropriate page.
=> Docs: Link to Devel&Prod pages in General

modules/base/admin/module.py
Users do not need access to these values, as it mostly represents
undisclosed internal state.
=> Admin: Increase 'config' command permissions

pie/utils/objects.py
Both ScrollableEmbed and ScrollableVotingEmbed now do not mention the
author and support as_reply argument.
=> Pie: Unify behavior of scrolling embeds

pie/utils/time.py, tests/pie/utils/test_time.py
While fuzzy-matching dates is nice, it has a problem of being unable to understand machine-friendly strings like the ISO 8601.
YYYY-xx-yy could be both YYYY-mm-dd and YYYY-dd-mm, depending on if the day is <= 12 or not.
I also updated the tests so they are parametrized, and each of the checks is done as separate test.
=> Add ISO 8601 as primary datetime parser

pie/utils/text.py, tests/pie/utils/test_text.py
Since the new Android app has been released a few weeks ago, we can enable colored tables in the output. Support for it has been present for several months now.
The colors are not visible on Android yet, but control characters are not being displayed anymore. Most of the administration is usually done on desktop.
We may add support for custom colors in the future, configurable by the server administrators, to allow synchronization with role or server colors.
=> pie: Enable colored tables

Dockerfile, docker-compose.yml
The .env file supplies runtime environment variables.  Not build-time variables. This is my solution to allow TZ to become a build variable.
If you convert TZ into an ARG in the Dockerfile, add it to the docker-compose.yml.  
Using `docker-compose build --build-arg "TZ=America/Phoenix"` will set the TZ at build.   
Use `docker-compose up -d` to start and `docker-compose stop` to gracefully stop.  
As well as `docker-compose logs -f` to follow the logs.
This does not work with `docker-compose up --build`.  There is no `--build-arg` for the `up` command.
=> TZ as ARG in Docker

pumpkin.py
We have had problems in a past with systems being set up improperly. Displaying all kind of versions (Python, system, repository hashes) could help with a lot of them.
=> pumpkin.py: Print debug information at the start

pie/logger/__init__.py
We are printing log messages to stdout, along with saving them to a log file. That is not a problem when the code is run directly in a terminal, because they tend to display text immediately. However, when the stdout is captured by systemd service, it can be held for quite a long time (over ten minutes). By force-flushing the `print` statement we should get nearly instant output.
=> pie: Force flush to stdout

modules/base/base/module.py, modules/base/po/cs.popie, modules/base/po/sk.popie
Hi, this is enhancement for bookmarker embeded. This can be useful when some user using it a lot. So the search will be easier when finding message from specific author. Now it's hard because it take only server or global user name which is easy to change so searching for specific user is hard.
I added it as first field after the content of bookmarked message.
=> Add author ID to bookmarker embeded.

docs/development/translations.rst
The translator always takes "modules/{repo}".
=> Docs: Fix i18n instructions

pumpkin.py
Recent debug-targeted commit 64be0c7 assumed every repository is a git repository. When it is not a case, the initialization would crash.
=> pumpkin.py: Handle non-git repositories

.gitignore, default.docker.env
Changed the default environment variable for docker backup to `./backups` to allow for more compatibility across platforms.
Added `backups/*` to `.gitignore`
=> moved docker backup

modules/base/admin/module.py
Now log message is different for updated and not updated repository. If repository is up to date it is mentioned with current hash otherwise log message is changed to show current and previous hash.
Resolves #312
=> Update repository logging

modules/base/base/module.py
It was possible to be immune from getting your reaction removed if user had blocked the bot. Fixed.
=> Base: Fixed userpin reaction protection.

default.docker.env, docker-compose.yml
Previously the name of the folder was used, then the breaking change to current state happened (and all instances are forcefully named pumpkin-...).
This change brings a ballance into these two approaches and allows the users to name the instances.
=> [Docker] Allow instance naming

modules/base/admin/module.py, modules/base/base/module.py, modules/base/baseinfo/module.py, pie/acl/__init__.py, pie/help.py, pie/i18n/database.py, pie/utils/time.py, pumpkin.py, requirements.txt
Changes made so far:
1. flake8 and black first to make the checks happy (as it would probably fail)
2. updated discord.py to newest version (as we are gonna work with Slash commands)
3. added support for Interaction check into ACL2
4. fixed synchronization of slash / hybrid commands (on bot start + on module manipulation)
5. Converted ping command to hybrid.
As I'm working with ACL2 checks, even though I've tested it, I'd anyway recommend other people to test it out, just to be on the safe side.
=> Add support for slash / hybrid commands
